### ISSUE TITLE
Feature : 공고 상세 페이지 구현

### ISSUE THREAD

**Issue by kimdanbin** [Step3-kakao-tech-campus/Team12_FE#34]
## Description
공고 상세 페이지 구현

## Todo
- [x] 파란색 영역(매칭을 기다리고 있어요.)
- [x] 주문 정보, 요청 사항, 마감기한
- [x] 이 음료 픽업하기 버튼

## ETC
기타사항
